`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 26.04.2026 15:16:36
// Design Name: 
// Module Name: ALUControl_Unit
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

/* BAsed on the Control Signal(ALUOp) generated by Control Unit and function field the ALUControl Unit
generates  ALUControl Signal on the basis of which ALu Performs Arithmetic Operation */   

module ALUControl_Unit(input [1:0]ALUOp,input [5:0]funct,output reg [2:0]ALUControl);
always@(*)
begin
case(ALUOp)
2'b00: ALUControl = 3'b010; // IF Load/Store/addi then Always Perform Add
2'b01: ALUControl = 3'b110; // IF beq(branch equal to) then always perform Sub
2'b10: begin  // IF R-Type Instruction then ALU Operation Depends on funct (Instruction[5:0])
       case(funct)
       6'h20: ALUControl = 3'b010; //Add
       6'h24: ALUControl = 3'b000; //AND
       6'h25: ALUControl = 3'b001; //OR
       6'h2a: ALUControl = 3'b111; //SLT(Set Less Than
       6'h22: ALUControl = 3'b110; //Sub
     default: ALUControl = 3'bx;   //Default to Dont'care
       endcase
       end
default: ALUControl = 3'b010; //Add
endcase
end       
endmodule

